### ISSUE TITLE
initSES failing for Chrome Beta 44

### ISSUE THREAD

**Issue by stephenKhuu** [google/caja#1971] opened 2015-07-10 18:22 UTC
On Mac OSX 10.10.4

trying to initialize caja with the following configuration:

      'cajaServer': this.server_.toString(),
      'debug': true,
      'maxAcceptableSeverity': 'NOT_OCAP_SAFE',
      'mitigateGotchas': false

but SES instantiation fails and returns the attached report in the console:
![image](https://cloud.githubusercontent.com/assets/12400542/8625682/5489f1fa-270e-11e5-92e9-e42d830288c4.png)

value of this.server_ is pointing to a hosted version of caja on our servers. The server is the Git hashed version v6000-23-gff10d92

**Comment by kpreid** [comment] 2015-07-10 18:42
This is a duplicate of issue #1966. It is fixed in release v6002.

**Closed by kpreid** 2015-07-10 18:42 UTC
