### ISSUE TITLE
SES needs to patch ES6 *Error [[Prototype]]

### ISSUE THREAD

**Issue by kpreid** [google/caja#1966] opened 2015-05-19 14:17 UTC
ES6 specifies that EvalError, RangeError, etc. have a [[Prototype]] of Error, as opposed to Function.prototype.

This is newly implemented, observed in Chrome 44.0.2398.0 dev and Chrome 45.0.2405.0 canary. This causes SES initialization to fail, since the non-whitelisted unsafe Error object is detected.

**Comment by erights** [comment] 2015-05-19 19:39
Visiting 
https://rawgit.com/google/caja/master/src/com/google/caja/ses/explicit.html
from Chrome 44.0.2403.4 dev (64-bit) on Mac OS 10.9.5, I do see

[-] 6 unexpected intrinsic. Not isolated(5) is not SES-safe.
EvalError.__proto__ RangeError.__proto__ ReferenceError.__proto__ SyntaxError.__proto__ TypeError.__proto__ URIError.__proto__

Fortunately, it is already fixed by 
https://codereview.appspot.com/226970043/
as demonstrated by visiting 
https://rawgit.com/tvcutsem/es-lab/master/src/ses/contract.html
Once Kevin is available again, we will check this in.

**Comment by erights** [comment] 2015-05-20 02:04
It is a duplicate of issue #1961

**Closed** 2015-05-20 02:06 UTC
Labels: duplicate
