### ISSUE TITLE
Caja doesn't load external javascript anymore

### ISSUE THREAD

**Issue by kurttomlinson** [google/caja#1980] opened 2015-09-12 16:23 UTC
My blog uses Caja to make JS safe inside blog posts. One page on my blog uses jQuery to link the scroll bars of two divs together. jQuery is no longer loading within a Caja frame for me.

[Example code inside my Caja frame](http://blog.bloopist.com/posts/jquery-scroll-lock-demo):
```
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
<div id="one" style="height:100px; overflow-y:scroll">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis tempus, neque eu dapibus porttitor, libero metus interdum lacus, in blandit neque nisl quis magna. Vivamus sodales vehicula augue, feugiat cursus ante. Sed dapibus cursus luctus. Curabitur euismod gravida felis, vitae varius lectus iaculis eu. Phasellus aliquet sapien at nulla varius finibus. Vivamus tortor libero, aliquam vitae lectus eget, facilisis eleifend lorem. Donec quis hendrerit magna, ac tincidunt sapien. Duis blandit, libero eu cursus aliquam, massa risus malesuada eros, luctus suscipit mi erat id turpis. Nulla vitae bibendum arcu. Curabitur viverra venenatis dictum. Quisque rhoncus pretium purus, sed venenatis velit laoreet ultrices. Proin non convallis felis. Sed ornare nisl nec libero dignissim mattis ut at felis.</div>

<div id="two" style="height:100px; overflow-y:scroll">課民的止低伊真場碁回社囲。勤治工合件情転平求供員皇暮。率輝済安質文詳佐業身漢囲際内阪。仰結聞涯間応演演玉冊転同戸禁移集。残府無著太断初豊表挙済主入約取略掲志門。投詳和西色渡解健報香都民輩要宝選覧議春国。更品際途接航君価有者竹催福内芸。減族女全約約予混大川権力質真。話加稿択碁百多要約職診竹意番走批。</div>

<script>
function print_scroll_one() {
	var y = $("#one").scrollTop();
	console.log("y=" + y);
	var height = $("#one").prop("scrollHeight");
	console.log("height=" + height);
}
function print_scroll_two() {
	var y = $("#two").scrollTop();
	console.log("y=" + y);
	var height = $("#two").prop("scrollHeight");
	console.log("height=" + height);
}
var ignore_scroll = false;
function one_to_two() {
	var y = $("#one").scrollTop();
	console.log("y=" + y);
	var height = $("#one").prop("scrollHeight");
	console.log("height=" + height);
	var percentage = y/height;
	var set_y = percentage * $("#two").prop("scrollHeight");
	ignore_scroll = true;
	$("#two").scrollTop(set_y);
}
function two_to_one() {
	var y = $("#two").scrollTop();
	console.log("y=" + y);
	var height = $("#two").prop("scrollHeight");
	console.log("height=" + height);
	var percentage = y/height;
	var set_y = percentage * $("#one").prop("scrollHeight");
	ignore_scroll = true;
	$("#one").scrollTop(set_y);
}
$( "#one" ).scroll(function() {
  if (ignore_scroll) {
	ignore_scroll = false;
  } else {
    one_to_two();
  }
});
$( "#two" ).scroll(function() {
  if (ignore_scroll) {
	ignore_scroll = false;
  } else {
    two_to_one();
  }
});
print_scroll();
</script>
```

Error:
![image](https://cloud.githubusercontent.com/assets/1914753/9832431/3a011e1c-5940-11e5-86e9-1c1f6ee47f42.png)

**Comment by kpreid** [comment] 2016-01-28 23:55
Duplicate of #1984.

**Closed by kpreid** 2016-01-28 23:55 UTC
