### ISSUE TITLE
Need to rewire Error inheritance to keep UnsafeError hidden

### ISSUE THREAD

**Issue by kpreid** [google/caja#1961] opened 2015-04-16 05:53 UTC
Original [issue 1963](https://code.google.com/p/google-caja/issues/detail?id=1963) created by erights on 2015-04-12T00:33:33.000Z:

For each of the builtin &quot;subclasses&quot; of Error, such as EvalError, ES6 changes them the constructors themselves to inherit directly from the Error constructor, in order to be analogous to ES6's handling of user defined classes. Chrome 44 Canary now implements this.

However, debug.js hides the original Error constructor for its own use as UnsafeError, replacing it with FakeError. However, it still would have been accessible via, for example, Object.getPrototypeOf(EvalError) or EvalError.__proto__. Fortunately, the new error checking we added to startSES caught this, so no unsafety results. Unfortunately, this results in SES (and therefore Caja in ES5 mode) reporting that it cannot initialize safely on Chrome 44 Canary.

**Comment by erights** [comment] 2015-05-20 02:09
Issue #1966 is a duplicate of this. 

(How do I mark duplicates so this booking happens automatically?)

**Comment by erights** [comment] 2015-05-21 23:39
https://codereview.appspot.com/226970043/

**Closed by erights** 2015-05-21 23:39 UTC
Labels: Component-Other, Priority-Medium, Type-Defect
