### ISSUE TITLE
playground: empty "cajoled source"

### ISSUE THREAD

**Issue by oresmus** [google/caja#2002] opened 2016-08-18 16:18 UTC
This is a bug in the Caja Playground. Following the instructions in the tutorial (with the canvas clock example), the contents under the "cajoled source" tab are just a 2-line empty &lt;script>&lt;/script>, not the cajoled source as expected.

Instructions to repeat this, in more detail: in the playground [http://caja.appspot.com/], (1) click the line which chooses that example, (2) click the Cajole button [clock is shown as expected, and is running], (3) click the Cajoled Source tab (empty script is shown).

This is in Google Chrome Version 52.0.2743.116 (64-bit) (latest), on a Mac running Yosemite (10.10.5).

(For some reason I'm unable to search open issues for text, so I can't be sure this isn't a known issue.)

**Comment by kpreid** [comment] 2016-08-18 16:30
Duplicate of #1504 .

The Playground UI design predates ES5 mode, in which case there is no “cajoling” and therefore no cajoled source to display. So, the fix here is to remove that tab (or rename it and use it to display a snapshot of the runtime-created HTML).

We're probably going to replace the Playground with something much simpler from scratch, once ES5/3 is truly dead and the cajoler is never needed.

**Closed by kpreid** 2016-08-18 16:30 UTC
